# fly.toml app configuration file generated for biomes-game on 2025-04-06T14:52:57Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'biomes-game'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 8
  memory_mb = 16384
