# fly.toml app configuration file
app = "biomes-game"
primary_region = "ams"

[build]
  # Use the Docker builder directly
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  NODE_ENV = "production"
  # Set to false based on local setup documentation
  DISCORD_HOOKS_ENABLED = "false"
  # Add logging environment variables
  DEBUG = "*"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  processes = ["app"]

# Explicitly set the command to run our entry point
[processes]
  app = "node /app/index.js"

# Start with a smaller VM for testing
[[vm]]
  cpu_kind = "shared"
  cpus = 8
  memory_mb = 16384
