# fly.toml app configuration file
app = "biomes-game"
primary_region = "waw"

[build]
  # Using the updated Dockerfile

[env]
  PORT = "8080"
  NODE_ENV = "production"
  # Add any other environment variables needed

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  processes = ["app"]

# Configuration for the VM - Note that 64GB memory is recommended
# but Fly.io may have limits on machine sizes
[[vm]]
  cpu_kind = "shared"
  cpus = 8
  memory_mb = 32768  # Maximum allowed or affordable
